import type { Metadata } from "next";
import localFont from "next/font/local";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const axiforma = localFont({
  src: [
    {
      path: "./axiforma/Axiforma_Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./axiforma/Axiforma_Light.ttf",
      weight: "300",
      style: "normal",
    },
    {
      path: "./axiforma/Axiforma_Medium.ttf",
      weight: "500",
      style: "normal",
    },
    {
      path: "./axiforma/Axiforma-Black.ttf",
      weight: "600",
      style: "normal",
    },
    {
      path: "./axiforma/Axiforma-Heavy.ttf",
      weight: "700",
      style: "normal",
    },
    {
      path: "./axiforma/Axiforma-Thin.ttf",
      weight: "200",
      style: "normal",
    },
  ],
});

export const metadata: Metadata = {
  title: "Pixel",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${axiforma.className}`}
      >
        {children}
      </body>
    </html>
  );
}
